CREATE TABLE aircrafts_tmp
    AS SELECT * FROM aircrafts;


SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

UPDATE aircrafts_tmp
    SET range = range + 100
    WHERE aircraft_code = 'SU9';

BEGIN ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

